
server:
  port: 8080
  servlet:
    contextPath: /booking-api

spring:
  application:
    name: booking-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect